ds_root: '/media/matteo/T7/Datasets/HyperSpectral/'

datasets: ['PRISMA']
sensor: 'PRISMA'

# experiment_folders: ['Full_Resolution', 'Reduced_Resolution']
experiment_folders: ['Reduced_Resolution']


algorithms: ['EXP',
             'GSA', 'BT-H', 'BDSD-PC', 'PRACS',
             'MTF-GLP-FS', 'MTF-GLP-HPM', 'MTF-GLP-HPM-R', 'AWLP', 'MF',
             'HySURE', 'SR-D', 'TV',
             'HyperPNN', 'HSpeNet', 'DHP-DARN', 'DIP-HyperKite', 'Hyper-DSNet', 'R-PNN', 'PCA-Z-PNN']

save_results: True

save_root: './Results'
save_assessment: './Assessment'