gpu_number: '3'
training_img_root: ''

train: False
validation: True

# Training settings
resume: False
save_weights: True
save_weights_path: 'weights'
save_training_stats: True

# Training hyperparameters
learning_rate: 0.0001
beta_1: 0.9
beta_2: 0.999
epochs: 4000
batch_size: 64
lambda_mse: 0.9
model_weights_path: ''







