gpu_number: '0'
model_weights_path: ''

training_img_root: ''

load_priors: True
save_priors: True

split_test_image_for_prior: False

# DHP Training hyperparameters
dhp_learning_rate: 0.01
beta_1: 0.9
beta_2: 0.999
epochs: 10000


# Training settings

train: False
validation: True
resume: False
save_weights: True
save_weights_path: 'weights'
save_training_stats: True


# DARN Training hyperparameters

darn_learning_rate: 0.001
darn_epochs: 1500
batch_size: 64





